services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OPENAI_API_KEY=NONE
    volumes:
      - open-webui:/app/backend/data
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3001:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
# Update Password
      - GF_SECURITY_ADMIN_PASSWORD=Ch@ngeMeN0w!
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

  comfyui:
    image: comfyui-cuda-12.5.1:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    ports:
      - 7860:7860
    volumes:
# Change volume to model location
      - $PWD/comfyui-models:/home/user/app/models

  registry:
    image: registry:2
    container_name: registry
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
# Update hostname as needed
      - REGISTRY_HTTP_HOST=https://registry.sealingfamily.com
    restart: always
    ports:
      - 5000:5000
    volumes:
# Change volume to where you want to store registry info
      - $PWD/registry-data:/var/lib/registry

volumes:
  prom_data:
  open-webui:
  registry-data:
